language: node_js
node_js:
  - "5.11"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - npm i
script:
  - npm run build:prod
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master